import type {
  CatcherDetailResponse,
  CatchersResponse,
  LeaderboardResponse,
} from "@catcher-intel/contracts";

export const catchersDemo: CatchersResponse = {
  season: 2025,
  catchers: [
    {
      catcher_id: 672275,
      catcher_name: "Adley Rutschman",
      team: "BAL",
      season: 2025,
      dropdown_label: "Adley Rutschman | BAL | 2025",
      headshot_url:
        "https://img.mlbstatic.com/mlb-photos/image/upload/w_180,q_auto:best/v1/people/672275/headshot/67/current",
      bats: "S",
      throws: "R",
      active: true,
    },
    {
      catcher_id: 669221,
      catcher_name: "William Contreras",
      team: "MIL",
      season: 2025,
      dropdown_label: "William Contreras | MIL | 2025",
      headshot_url:
        "https://img.mlbstatic.com/mlb-photos/image/upload/w_180,q_auto:best/v1/people/669221/headshot/67/current",
      bats: "R",
      throws: "R",
      active: true,
    },
    {
      catcher_id: 663728,
      catcher_name: "Cal Raleigh",
      team: "SEA",
      season: 2025,
      dropdown_label: "Cal Raleigh | SEA | 2025",
      headshot_url:
        "https://img.mlbstatic.com/mlb-photos/image/upload/w_180,q_auto:best/v1/people/663728/headshot/67/current",
      bats: "S",
      throws: "R",
      active: true,
    },
  ],
};

export const leaderboardDemo: LeaderboardResponse = {
  season: 2025,
  leaderboard: [
    {
      catcher_id: 672275,
      catcher_name: "Adley Rutschman",
      team: "BAL",
      season: 2025,
      headshot_url: catchersDemo.catchers[0]?.headshot_url,
      games_scored: 98,
      pitches: 5400,
      total_dva: 24.4,
      avg_dva: 0.0045,
      avg_execution_gap: 0.0012,
      outperform_rate: 0.56,
      qualified_for_grades: true,
      stability_label: "High stability",
      stability_note: "Demo sample only.",
      grades: {
        overall_game_calling: { score: 67.8, label: "Plus", qualified: true },
        count_leverage: { score: 64.3, label: "Plus", qualified: true },
        putaway_count: { score: 69.1, label: "Plus", qualified: true },
        damage_avoidance: { score: 63.4, label: "Plus", qualified: true },
        pitch_mix_synergy: { score: 66.2, label: "Plus", qualified: true },
        receiving_support: { score: 61.1, label: "Plus", qualified: true },
      },
      public_metrics: {
        framing_runs: 7.2,
        blocking_runs: 2.1,
        blocks_above_average: 5.6,
        pop_time_2b: 1.94,
        arm_overall: 86.9,
        max_arm_strength: 87.8,
      },
    },
    {
      catcher_id: 663728,
      catcher_name: "Cal Raleigh",
      team: "SEA",
      season: 2025,
      headshot_url: catchersDemo.catchers[2]?.headshot_url,
      games_scored: 95,
      pitches: 5220,
      total_dva: 21.5,
      avg_dva: 0.0041,
      avg_execution_gap: -0.0008,
      outperform_rate: 0.54,
      qualified_for_grades: true,
      stability_label: "High stability",
      stability_note: "Demo sample only.",
      grades: {
        overall_game_calling: { score: 65.1, label: "Plus", qualified: true },
        count_leverage: { score: 62.0, label: "Plus", qualified: true },
        putaway_count: { score: 63.4, label: "Plus", qualified: true },
        damage_avoidance: { score: 61.7, label: "Plus", qualified: true },
        pitch_mix_synergy: { score: 60.9, label: "Plus", qualified: true },
        receiving_support: { score: 58.4, label: "Solid", qualified: true },
      },
      public_metrics: {
        framing_runs: 5.5,
        blocking_runs: 1.8,
        blocks_above_average: 4.2,
        pop_time_2b: 1.97,
        arm_overall: 85.2,
        max_arm_strength: 86.4,
      },
    },
  ],
};

export const catcherDetailDemo: CatcherDetailResponse = {
  identity: {
    catcher_id: 672275,
    catcher_name: "Adley Rutschman",
    team: "BAL",
    season: 2025,
    headshot_url: catchersDemo.catchers[0]?.headshot_url,
    bats: "S",
    throws: "R",
    active: true,
    dropdown_label: "Adley Rutschman | BAL | 2025",
  },
  total_pitches: 5400,
  total_dva: 24.4,
  avg_dva: 0.0045,
  avg_execution_gap: 0.0012,
  grades: leaderboardDemo.leaderboard[0]!.grades,
  public_metrics: {
    framing_runs: 7.2,
    blocking_runs: 2.1,
    blocks_above_average: 5.6,
    pop_time_2b: 1.94,
    arm_overall: 86.9,
    max_arm_strength: 87.8,
    source_note:
      "Framing, blocking, pop time, and arm strength sourced from public Baseball Savant leaderboards.",
  },
  diagnostics: {
    games_scored: 98,
    avg_expected_rv_actual: -0.013,
    outperform_rate: 0.56,
    avg_surviving_candidate_count: 2.7,
    single_candidate_pct: 0.18,
    dropped_sparse_context_pct: 0.12,
    fallback_context_pct: 0.21,
    qualified_for_grades: true,
    stability_label: "High stability",
    stability_note: "Demo sample only.",
    model_version: "dva_v1_contextual",
  },
  grade_formula_notes: {
    overall_game_calling: {
      description:
        "45% avg DVA, 20% baseline outperformance rate, 20% hitter-friendly count DVA, 15% put-away count DVA.",
    },
    count_leverage: {
      description: "65% hitter-friendly count DVA, 35% hitter-friendly outperformance rate.",
    },
    putaway_count: {
      description: "70% put-away count DVA, 30% put-away outperformance rate.",
    },
    damage_avoidance: {
      description: "55% lower-is-better expected run value in damage counts, 45% damage-count DVA.",
    },
    pitch_mix_synergy: {
      description:
        "40% count-family alignment rate, 40% pitcher-pairing avg DVA, 20% pitcher-pairing outperformance rate.",
    },
    receiving_support: {
      description:
        "40% public framing runs, 25% blocking runs, 20% arm overall, 15% lower-is-better pop time to second.",
    },
  },
  summary_insights: [
    {
      key: "overall_profile",
      label: "Strength",
      headline: "Overall game calling is the clearest carrying tool.",
      detail:
        "Adley Rutschman carries a Plus overall game-calling grade with +24.400 total DVA, +0.00450 avg DVA, and 56.0% baseline outperformance.",
      tone: "positive",
    },
    {
      key: "situational_edge",
      label: "Situational edge",
      headline: "0-2 is the best value pocket.",
      detail:
        "The strongest exact-count edge is 0-2 at +0.0069 avg DVA across 420 pitches, with breaker as the best-performing family signal.",
      tone: "positive",
    },
    {
      key: "pitch_pairing_edge",
      label: "Pitch + pairing edge",
      headline: "Pitch mix and battery fit add most of the secondary value.",
      detail:
        "Slider is the best pitch-type result, and the strongest pairing is with the top starter group in the demo sample.",
      tone: "positive",
    },
    {
      key: "weakness",
      label: "Weakness",
      headline: "3-1 is the main pressure point.",
      detail:
        "The weakest exposed exact-count pocket in the demo sample is 3-1, where hitter-friendly leverage narrows the margin for error.",
      tone: "caution",
    },
    {
      key: "confidence",
      label: "Data confidence",
      headline: "The sample is trustworthy enough for season-level scouting.",
      detail:
        "High stability at 5,400 pitches across 98 games, with 12.0% sparse-context drops and +0.0012 avg execution gap in the demo payload.",
      tone: "positive",
    },
  ],
  count_state_summaries: [
    {
      split_type: "count_state",
      split_value: "0-0",
      pitches: 810,
      total_dva: 3.7,
      avg_dva: 0.0046,
      avg_execution_gap: 0.0008,
      avg_expected_rv_actual: -0.009,
      outperform_rate: 0.55,
      fastball_rate: 0.48,
      breaker_rate: 0.31,
      offspeed_rate: 0.21,
      fastball_dva: 0.0032,
      breaker_dva: 0.0051,
      offspeed_dva: 0.0048,
      actual_top_pitch_family: "fastball",
      recommended_pitch_family: "breaker",
      hitter_friendly_flag: false,
      pitcher_friendly_flag: false,
      putaway_flag: false,
      sample_label: "Stable split",
      low_sample: false,
    },
    {
      split_type: "count_state",
      split_value: "0-2",
      pitches: 420,
      total_dva: 2.9,
      avg_dva: 0.0069,
      avg_execution_gap: 0.0011,
      avg_expected_rv_actual: -0.032,
      outperform_rate: 0.61,
      fastball_rate: 0.22,
      breaker_rate: 0.49,
      offspeed_rate: 0.29,
      fastball_dva: 0.0015,
      breaker_dva: 0.0081,
      offspeed_dva: 0.0074,
      actual_top_pitch_family: "breaker",
      recommended_pitch_family: "breaker",
      hitter_friendly_flag: false,
      pitcher_friendly_flag: true,
      putaway_flag: true,
      sample_label: "Stable split",
      low_sample: false,
    },
    {
      split_type: "count_state",
      split_value: "3-1",
      pitches: 205,
      total_dva: 0.9,
      avg_dva: 0.0044,
      avg_execution_gap: -0.0005,
      avg_expected_rv_actual: 0.019,
      outperform_rate: 0.52,
      fastball_rate: 0.58,
      breaker_rate: 0.18,
      offspeed_rate: 0.24,
      fastball_dva: 0.0037,
      breaker_dva: 0.0048,
      offspeed_dva: 0.0051,
      actual_top_pitch_family: "fastball",
      recommended_pitch_family: "offspeed",
      hitter_friendly_flag: true,
      pitcher_friendly_flag: false,
      putaway_flag: false,
      sample_label: "Stable split",
      low_sample: false,
    },
  ],
  count_bucket_summaries: [
    {
      split_type: "count_bucket",
      split_value: "pitcher_ahead",
      pitches: 2120,
      total_dva: 11.2,
      avg_dva: 0.0053,
      avg_execution_gap: 0.0016,
      avg_expected_rv_actual: -0.026,
      outperform_rate: 0.58,
      fastball_rate: 0.34,
      breaker_rate: 0.42,
      offspeed_rate: 0.24,
      fastball_dva: 0.0033,
      breaker_dva: 0.0068,
      offspeed_dva: 0.0054,
      actual_top_pitch_family: "breaker",
      recommended_pitch_family: "breaker",
      hitter_friendly_flag: false,
      pitcher_friendly_flag: true,
      putaway_flag: false,
      sample_label: "Stable split",
      low_sample: false,
    },
    {
      split_type: "count_bucket",
      split_value: "even",
      pitches: 1630,
      total_dva: 6.1,
      avg_dva: 0.0037,
      avg_execution_gap: 0.0006,
      avg_expected_rv_actual: -0.011,
      outperform_rate: 0.54,
      fastball_rate: 0.44,
      breaker_rate: 0.33,
      offspeed_rate: 0.23,
      fastball_dva: 0.0031,
      breaker_dva: 0.0042,
      offspeed_dva: 0.0039,
      actual_top_pitch_family: "fastball",
      recommended_pitch_family: "breaker",
      hitter_friendly_flag: false,
      pitcher_friendly_flag: false,
      putaway_flag: false,
      sample_label: "Stable split",
      low_sample: false,
    },
    {
      split_type: "count_bucket",
      split_value: "hitter_ahead",
      pitches: 1190,
      total_dva: 5.4,
      avg_dva: 0.0045,
      avg_execution_gap: 0.0001,
      avg_expected_rv_actual: 0.012,
      outperform_rate: 0.55,
      fastball_rate: 0.52,
      breaker_rate: 0.19,
      offspeed_rate: 0.29,
      fastball_dva: 0.0038,
      breaker_dva: 0.0041,
      offspeed_dva: 0.0059,
      actual_top_pitch_family: "fastball",
      recommended_pitch_family: "offspeed",
      hitter_friendly_flag: true,
      pitcher_friendly_flag: false,
      putaway_flag: false,
      sample_label: "Stable split",
      low_sample: false,
    },
  ],
  pitch_type_summaries: [
    {
      pitch_type: "SL",
      pitch_family: "breaker",
      pitches: 1320,
      total_dva: 7.1,
      avg_dva: 0.0054,
      avg_execution_gap: 0.0012,
      avg_expected_rv_actual: -0.024,
      outperform_rate: 0.58,
    },
    {
      pitch_type: "FF",
      pitch_family: "fastball",
      pitches: 1480,
      total_dva: 6.2,
      avg_dva: 0.0042,
      avg_execution_gap: 0.0006,
      avg_expected_rv_actual: -0.017,
      outperform_rate: 0.55,
    },
    {
      pitch_type: "CH",
      pitch_family: "offspeed",
      pitches: 910,
      total_dva: 4.3,
      avg_dva: 0.0047,
      avg_execution_gap: 0.0011,
      avg_expected_rv_actual: -0.018,
      outperform_rate: 0.57,
    },
  ],
  pairings: [
    {
      pitcher_id: 669302,
      pitcher_name: "Grayson Rodriguez",
      pitches: 980,
      total_dva: 4.8,
      avg_dva: 0.0049,
      avg_execution_gap: 0.0007,
      avg_expected_rv_actual: -0.019,
      outperform_rate: 0.57,
    },
    {
      pitcher_id: 656302,
      pitcher_name: "Kyle Bradish",
      pitches: 815,
      total_dva: 3.9,
      avg_dva: 0.0048,
      avg_execution_gap: 0.0011,
      avg_expected_rv_actual: -0.021,
      outperform_rate: 0.58,
    },
    {
      pitcher_id: 641649,
      pitcher_name: "Corbin Burnes",
      pitches: 760,
      total_dva: 3.1,
      avg_dva: 0.0041,
      avg_execution_gap: -0.0003,
      avg_expected_rv_actual: -0.023,
      outperform_rate: 0.55,
    },
  ],
  matchup_summaries: [
    {
      stand: "R",
      p_throws: "R",
      matchup_label: "R bat / R throw",
      pitches: 2410,
      total_dva: 11.7,
      avg_dva: 0.0049,
      avg_execution_gap: 0.0008,
      outperform_rate: 0.57,
    },
    {
      stand: "L",
      p_throws: "R",
      matchup_label: "L bat / R throw",
      pitches: 1890,
      total_dva: 8.1,
      avg_dva: 0.0043,
      avg_execution_gap: 0.0012,
      outperform_rate: 0.54,
    },
  ],
};
